routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('tickets/assigned', 'TicketsActionController@assigned')->name('tickets.assigned');
Route::put('tickets/{ticket}/complete', 'TicketsActionController@complete')->name('tickets.complete');
Route::get('tickets/completed', 'TicketsActionController@completed')->name('tickets.completed');
Route::get('tickets/resolved', 'TicketsActionController@resolved')->name('tickets.resolved');

Route::get('tickets/raised', 'TicketsActionController@raised')->name('tickets.raised');
Route::get('tickets/resolve', 'TicketsActionController@toBeResolve')->name('tickets.toBeResolve');
Route::put('tickets/{ticket}/resolve', 'TicketsActionController@resolve')->name('tickets.resolve');
Route::put('tickets/{ticket}/unresolve', 'TicketsActionController@unresolve')->name('tickets.unresolve');
Route::put('tickets/{ticket}/reassign', 'TicketsActionController@reassign')->name('tickets.reassign');

Route::resource('tickets', 'TicketsController');

Route::get('users/notifications', 'UserController@notifications')->name('user.notifications');
Route::post('users/best-employee', 'UserController@bestEmployee')->name('user.best-employee');
Route::get('users/profile', 'UserController@profile')->name('user.profile');

app/Ticket.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Ticket extends Model
{
    protected $fillable = [
        'title',
        'description',
        'user_id'
    ];

    /**
     * HELPER FUNCTION
     */
    

    /**
     * ACCESSORS Functions
     */
    public function getCreatedDateAttribute()
    {
        return $this->created_at->diffForHumans();
    }

    /**
     * RELATIONSHIP METHODS
     */

    //Ticket raised by
    public function owner()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    //ticket_user table
    public function assigned()
    {
        return $this->belongsToMany(User::class)->withTimestamps();
    }

    //status_code_ticket table
    public function status()
    {
        return $this->belongsToMany(StatusCode::class, 'status_code_ticket')->withPivot('created_at')
            ->orderBy('status_code_ticket.created_at')
            ->withTimestamps();
    }
}

app/Http/Controllers/TicketsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateTicketRequest;
use App\Notifications\TicketAssigned;
use App\Ticket;
use App\User;
use Illuminate\Http\Request;

class TicketsController extends Controller
{

    public function __construct()
    {
        $this->middleware(['auth'])->only(['create', 'store', 'show']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $users = User::all();
        $teamMembers = $users->where('role', 'team-member');
        $notifications = UserController::notifications();
        return view('tickets.create', compact([
            'teamMembers',
            'notifications'
        ]));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateTicketRequest $request)
    {
        $ticket = auth()->user()->raised()->create([
            'title' => $request->title,
            'description' => $request->description,
            'user_id' => auth()->id()
        ]);

        if($request->assignment == 'auto')
        {
            $teamMember = User::where('role', 'team-member')->get()->random();
        }
        else if($request->assignment == 'manual')
        {
            $teamMember = User::find($request->manual_assign_id);
        }
        $teamMember->assigned()->attach([$ticket->id]);
        $ticket->status()->attach([1]);

        $ticket->assigned->last()->notify(new TicketAssigned($ticket));

        session()->flash('success', 'Ticket created and assigned successfully');

        return redirect(route('tickets.raised'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Ticket  $ticket
     * @return \Illuminate\Http\Response
     */
    public function show(Ticket $ticket)
    {
        $notifications = UserController::notifications();
        return view('tickets.show', compact([
            'ticket',
            'notifications'
        ]));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Ticket  $ticket
     * @return \Illuminate\Http\Response
     */
    public function edit(Ticket $ticket)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Ticket  $ticket
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Ticket $ticket)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Ticket  $ticket
     * @return \Illuminate\Http\Response
     */
    public function destroy(Ticket $ticket)
    {
        // dd($this);
        if($this->authorize('delete', $ticket))
        {
            $ticket->delete();
            session()->flash('success', 'Ticket has been deleted successfully!');
            return redirect(route('tickets.raised'));
        }
        abort(403);
    }
}

resources/views/tickets/create.blade.php
@extends('layouts.app')

@section('title', 'New Ticket')

@section('content')
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header"><h3>Ticket</h3></div>
                    <div class="card-body">
                        <form action="{{ route('tickets.store') }}" method="POST">
                            @csrf
                            <div class="form-group">
                                <label for="title">Title</label>
                                <input type="text"
                                    id="title"
                                    name="title"
                                    placeholder="Enter Title"
                                    value = "{{ old('title') }}"
                                    class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}">
                                @error('title')
                                    <div class="text-danger">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <input id="description" 
                                    type="hidden" 
                                    name="description" 
                                    value="{{ old('description') }}">
                                <trix-editor input="description"></trix-editor>
                                @error('description')
                                    <div class="text-danger">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="assignment" id="autoAssign" value="auto" checked>
                                <label class="form-check-label" for="autoAssign">
                                    Auto Assign
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="assignment" id="manualAssign" value="manual">
                                <label class="form-check-label" for="manualAssign">
                                    Manual Assign
                                </label>
                            </div>

                            <div class="form-group col-md-6 mt-4 d-none p-0" id="team-members">
                                <label for="manual_assign_id">Members</label>
                                <select id="manual_assign_id" class="form-control" name="manual_assign_id">
                                    <option selected disabled>Choose...</option>
                                    @foreach($teamMembers as $teamMember)
                                        <option value="{{ $teamMember->id }}">{{ $teamMember->name }}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="form-group">
                                <button type="submit" class="btn btn-outline-success mt-4">Assign</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div> 
        </div>
    </div>
@endsection

@section('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.1/trix.js"></script>
    <script>
        var manualAssign = document.getElementById('manualAssign');
        manualAssign.addEventListener('change', function(){
            var teamMembers = document.getElementById('team-members');
            if(this.checked == true){
                // console.log(teamMembers);
                teamMembers.classList.toggle('d-none');
            }   
        });

        var autoAssign = document.getElementById('autoAssign');
        autoAssign.addEventListener('change', function(){
            var teamMembers = document.getElementById('team-members');
            if(this.checked == true){
                // console.log(teamMembers);
                teamMembers.classList.add('d-none');
            }   
        });
    </script>
@endsection

@section('styles')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.1/trix.css">
@endsection

resources/views/tickets/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid mt-3">
        <div class="row">
            <div class="col-md-12">
                <div class="d-flex justify-content-between">
                    <h4 class="text-primary">Tickets</h4>
                </div>

                <div class="">
                    @foreach($tickets as $ticket)
                            <div class="card shadow">
                                <div class="card-body">
                                    <div>
                                        <div class="d-flex justify-content-between">
                                            <div class="text-center mt-2">
                                                <a href="{{ route('tickets.show', $ticket) }}">{!! $ticket->title !!}</a>
                                            </div>

                                            <div class="text-center mt-2">
                                                @can('complete', $ticket)
                                                    <form action="{{ route('tickets.complete', $ticket->id) }}" method="POST">
                                                        @csrf 
                                                        @method('PUT')
                                                        <button class="btn btn-outline-success btn-sm">Complete</button>
                                                    </form>
                                                @endcan

                                                @can('delete', $ticket)
                                                    <form action="{{ route('tickets.destroy', $ticket->id) }}" method="POST">
                                                        @csrf 
                                                        @method('DELETE')
                                                        <button class="btn btn-outline-danger btn-sm mr-3">Delete</button>
                                                    </form>
                                                @endcan

                                                <div class="text-center d-flex justify-content-between mt-2">  

                                                    @can('resolveUnresolve', $ticket)
                                                        <form action="{{ route('tickets.resolve', $ticket->id) }}" method="POST">
                                                            @csrf 
                                                            @method('PUT')
                                                            <button class="btn btn-outline-success btn-sm mr-3">Resolve</button>
                                                        </form>

                                                        <form action="{{ route('tickets.unresolve', $ticket->id) }}" method="POST">
                                                            @csrf 
                                                            @method('PUT')
                                                            <button class="btn btn-outline-danger btn-sm">Unresolve</button>
                                                        </form>
                                                    @endcan

                                                </div>
                                            </div>

                                        </div>

                                        <div class="mt-2">
                                            {!! $ticket->description !!}
                                        </div>

                                        <div class="mt-2">
                                            <small>
                                                    @if(!auth()->user()->isTeamLeader())
                                                        <a href="#" class="text-muted"><i class="fa fa-pen mr-1"></i> {{$ticket->owner->name}} 
                                                    @else
                                                        <a href="#" class="text-muted"><i class="fa fa-user mr-1"></i> {{$ticket->assigned->first()->name}} 
                                                    @endif
                                            </a><span class="text-muted">|<i class="fa fa-pencil ml-1"></i>{{$ticket->created_date}}</span>
                                            </small>
                                        </div>
                                    
                                    </div>
                                </div>
                            </div>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/tickets/reassign.blade.php
@extends('layouts.app')

@section('title', 'Reassign')

@section('content')
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header"><h3>Ticket</h3></div>
                    <div class="card-body">
                        <form action="{{ route('tickets.reassign', $ticket->id) }}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label for="title">Title</label>
                                <input type="text"
                                    id="title"
                                    name="title"
                                    placeholder="Enter Title"
                                    value = "{{ $ticket->title }}"
                                    class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}" readonly>
                            </div>

                            <div class="form-group">
                                <label for="exampleFormControlTextarea1">Description</label>
                                <textarea class="form-control" id="description" name="description" rows="3" readonly>{!! $ticket->description !!}</textarea>
                            </div>

                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="assignment" id="autoAssign" value="auto">
                                <label class="form-check-label" for="autoAssign">
                                    Auto Assign
                                </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="assignment" id="manualAssign" value="manual" checked>
                                <label class="form-check-label" for="manualAssign">
                                    Manual Assign
                                </label>
                            </div>

                            <div class="form-group col-md-6 mt-4 d-block p-0" id="team-members">
                                <label for="manual_assign_id">Members</label>
                                <select id="manual_assign_id" class="form-control" name="manual_assign_id">
                                    <option selected disabled>Choose...</option>
                                    @foreach($teamMembers as $teamMember)
                                        <option value="{{ $teamMember->id }}" {{ $ticket->assigned->first()->name == $teamMember->name ? 'selected' : '' }}>{{ $teamMember->name }}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="form-group">
                                <button type="submit" class="btn btn-outline-success mt-4">Reassign</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div> 
        </div>
    </div>
@endsection

@section('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.1/trix.js"></script>
    <script>
        var manualAssign = document.getElementById('manualAssign');
        manualAssign.addEventListener('change', function(){
            var teamMembers = document.getElementById('team-members');
            if(this.checked == true){
                // console.log(teamMembers);
                teamMembers.classList.toggle('d-block');
            }   
        });

        var autoAssign = document.getElementById('autoAssign');
        autoAssign.addEventListener('change', function(){
            var teamMembers = document.getElementById('team-members');
            if(this.checked == true){
                // console.log("Here");
                // console.log(teamMembers);
                teamMembers.classList.remove('d-block');
                teamMembers.classList.add('d-none');
            }   
        });
    </script>
@endsection

@section('styles')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.1/trix.css">
@endsection

resources/views/tickets/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container mt-5">
    <div class="row">
        <div class="col-md-12">
            <div class="card card-shadow">
                <div class="card header"></div>
                <div class="card-body">
                    <div>
                        <div class="d-flex justify-content-between">
                            <div class="text-center mt-2">
                                <h4 class="text-muted">{!! $ticket->title !!}</h4>
                            </div>

                            <div class="text-center mt-2">
                                <small>
                                    @if(!auth()->user()->isTeamLeader())
                                        <a href="#" class="text-muted"><i class="fa fa-pen mr-1"></i> {{$ticket->owner->name}} 
                                    @else
                                        <a href="#" class="text-muted"><i class="fa fa-user mr-1"></i> {{$ticket->assigned->first()->name}} 
                                    @endif
                            </a><span class="text-muted">|<i class="fa fa-pencil ml-1"></i>{{$ticket->created_date}}</span>
                                </small>
                            </div>
                        </div>

                        <div class="mt-2">
                            <p>{!! $ticket->description !!}</p>
                        </div>
                    </div>
                    <div class="text-center">
                        @can('complete', $ticket)
                            <form action="{{ route('tickets.complete', $ticket->id) }}" method="POST">
                                @csrf 
                                @method('PUT')
                                <button class="btn btn-outline-success btn-sm">Complete</button>
                            </form>
                        @endcan
                    </div>
                    
                    <div class="text-center d-flex justify-content-between mt-2">    
                        @can('resolveUnresolve', $ticket)
                            <form action="{{ route('tickets.resolve', $ticket->id) }}" method="POST">
                                @csrf 
                                @method('PUT')
                                <button class="btn btn-outline-success btn-sm mr-3">Resolve</button>
                            </form>
                            <form action="{{ route('tickets.unresolve', $ticket->id) }}" method="POST">
                                @csrf 
                                @method('PUT')
                                <button class="btn btn-outline-danger btn-sm">Unresolve</button>
                            </form>
                        @endcan

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection