routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('tickets/assigned', 'TicketsActionController@assigned')->name('tickets.assigned');
Route::put('tickets/{ticket}/complete', 'TicketsActionController@complete')->name('tickets.complete');
Route::get('tickets/completed', 'TicketsActionController@completed')->name('tickets.completed');
Route::get('tickets/resolved', 'TicketsActionController@resolved')->name('tickets.resolved');

Route::get('tickets/raised', 'TicketsActionController@raised')->name('tickets.raised');
Route::get('tickets/resolve', 'TicketsActionController@toBeResolve')->name('tickets.toBeResolve');
Route::put('tickets/{ticket}/resolve', 'TicketsActionController@resolve')->name('tickets.resolve');
Route::put('tickets/{ticket}/unresolve', 'TicketsActionController@unresolve')->name('tickets.unresolve');
Route::put('tickets/{ticket}/reassign', 'TicketsActionController@reassign')->name('tickets.reassign');

Route::resource('tickets', 'TicketsController');

Route::get('users/notifications', 'UserController@notifications')->name('user.notifications');
Route::post('users/best-employee', 'UserController@bestEmployee')->name('user.best-employee');
Route::get('users/profile', 'UserController@profile')->name('user.profile');

resources/views/layouts/_footer.blade.php
<footer class="footer container sticky-bottom pt-0">
    <div class="row align-items-center justify-content-lg-between">
        <div class="col-lg-6">
        <div class="copyright text-center  text-lg-left  text-muted">
            &copy; 2020 <a href="https://gitlab.com/SakshiShah/ticket-management" class="font-weight-bold ml-1" target="_blank">Ticket Management</a>
        </div>
        </div>
        <div class="col-lg-6">
        <ul class="nav nav-footer justify-content-center justify-content-lg-end">
            <li class="nav-item">
            <a href="https://gitlab.com/SakshiShah" class="nav-link" target="_blank">Sakshi Shah</a>
            </li>
        </ul>
        </div>
    </div>
</footer>

resources/views/layouts/_message.blade.php
<div class="row">
    <div class="col-md-12">
        @if(session()->has('success'))
            <div class="alert alert-success alert-dismissible fade show">
                {{ session()->get('success') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true"></span>
                    </button>
            </div>
        @endif

        @if(session()->has('error'))
            <div class="alert alert-danger alert-dismissible fade show">
                {{ session()->get('error') }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true"></span>
                    </button>
            </div>
        @endif
    </div>
</div>

resources/views/layouts/_navbar.blade.php
@auth
<nav class="navbar navbar-top navbar-expand navbar-dark bg-primary border-bottom">
    <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    
        <!-- Navbar links -->
        <ul class="navbar-nav align-items-center  ml-md-auto ">

            <li class="nav-item d-xl-none">
                <!-- Sidenav toggler -->
                <div class="pr-3 sidenav-toggler sidenav-toggler-dark" data-action="sidenav-pin" data-target="#sidenav-main">
                <div class="sidenav-toggler-inner">
                    <i class="sidenav-toggler-line"></i>
                    <i class="sidenav-toggler-line"></i>
                    <i class="sidenav-toggler-line"></i>
                </div>
                </div>
            </li>
            <li class="nav-item d-sm-none">
                <a class="nav-link" href="#" data-action="search-show" data-target="#navbar-search-main">
                <i class="ni ni-zoom-split-in"></i>
                </a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link" href="{{ route('user.notifications') }}" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="ni ni-bell-55"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-xl  dropdown-menu-right  py-0 overflow-hidden">
                <!-- Dropdown header -->
                <div class="px-3 py-3">
                    <h6 class="text-sm text-muted m-0">You have <strong class="text-primary">{{$notifications->count()}}</strong> notifications.</h6>
                </div>
                <!-- List group -->
                <div class="list-group list-group-flush">
                @if(isset($notifications))
                    @foreach($notifications as $notification)
                        <a href="{{route('tickets.show', $notification->data['ticket']['id'])}}" class="list-group-item list-group-item-action">
                        <div class="row align-items-center">
                            <div class="col ml-2">
                                @if($notification->type === "App\Notifications\TicketAssigned")
                                    <p class="text-sm mb-0">A Ticket has been assigned to you!</p>
                                @endif

                                @if($notification->type === "App\Notifications\TicketCompleted")
                                    <p class="text-sm mb-0">Hurray! Your Ticket was completed!</p>
                                @endif

                                @if($notification->type === "App\Notifications\TicketResolved")
                                    <p class="text-sm mb-0">Hurray! Your Ticket was resolved!</p>
                                @endif

                                @if($notification->type === "App\Notifications\TicketUnresolved")
                                    <p class="text-sm mb-0">Sorry! Your Ticket was unresolved!</p>
                                @endif

                                <div class="d-flex justify-content-between align-items-center">
                                    <div class=""></div>
                                    <div class="text-right text-muted">
                                    <small>{{ $notification->created_at->diffForHumans() }}</small>
                                    </div>
                                </div>
                            </div>
                        </div>
                        </a>
                    @endforeach
                @endif
                    
            </li>
        </ul>
        <ul class="navbar-nav align-items-center  ml-auto ml-md-0 ">
            @guest
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                </li>
                @if (Route::has('register'))
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                    </li>
                @endif
            @else
                <li class="nav-item dropdown">
                    <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <div class="media align-items-center">
                        <span class="avatar avatar-sm rounded-circle">
                        <img alt="Image placeholder" src="{{ \Thomaswelton\LaravelGravatar\Facades\Gravatar::src(auth()->user()->email) }}">
                        </span>
                        <div class="media-body  ml-2  d-none d-lg-block">
                        <span class="mb-0 text-sm  font-weight-bold">{{auth()->user()->name}}</span>
                        </div>
                    </div>
                    </a>
                    <div class="dropdown-menu  dropdown-menu-right ">
                        <div class="dropdown-header noti-title">
                            <h6 class="text-overflow m-0">Welcome!</h6>
                        </div>
                        <a href="{{ route('user.profile')}}" class="dropdown-item">
                            <i class="ni ni-single-02"></i>
                            <span>My profile</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                        document.getElementById('logout-form').submit();">
                            <i class="ni ni-user-run"></i>
                            <span>Logout</span>
                        </a>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </div>
                </li>
            @endguest
        </ul>
    </div>
    </div>
</nav>


@endauth

resources/views/layouts/_sidebar.blade.php
@auth
<nav class="sidenav navbar navbar-vertical  fixed-left  navbar-expand-xs navbar-light bg-white" id="sidenav-main">
    <div class="scrollbar-inner">
      <!-- Brand -->
      <div class="sidenav-header  align-items-center">
        <a class="navbar-brand" href="javascript:void(0)">
          <i class="ni ni-app text-primary display-3"></i>
        </a>
      </div>
      <div class="navbar-inner">
        <!-- Collapse -->
        <div class="collapse navbar-collapse" id="sidenav-collapse-main">
          <!-- Nav items -->
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link {{Request::route()->getName() == 'home' ? 'active' : ''}}" href="{{ route('home') }}">
                <i class="ni ni-tv-2 text-primary"></i>
                <span class="nav-link-text">Dashboard</span>
              </a>
            </li>
          
            @if(!auth()->user()->isTeamLeader())
            <li class="nav-item">
              <a class="nav-link {{Request::route()->getName() == 'tickets.assigned' ? 'active' : ''}}" href="{{ route('tickets.assigned') }}">
                <i class="ni ni-curved-next text-primary"></i>
                <span class="nav-link-text">Assigned</span>
              </a>
            </li>

            <li class="nav-item">
              <a class="nav-link {{Request::route()->getName() == 'tickets.completed' ? 'active' : ''}}" href="{{ route('tickets.completed') }}">
                <i class="ni ni-like-2 text-primary"></i>
                <span class="nav-link-text">Completed</span>
              </a>
            </li>
            @endif

            @if(auth()->user()->isTeamLeader())
            <li class="nav-item">
              <a class="nav-link {{Request::route()->getName() == 'tickets.raised' ? 'active' : ''}}" href="{{route('tickets.raised')}}">
                <i class="ni ni-fat-add text-primary"></i>
                <span class="nav-link-text">Raised</span>
              </a>
            </li>

            <li class="nav-item">
              <a class="nav-link {{Request::route()->getName() == 'tickets.toBeResolve' ? 'active' : ''}}" href="{{ route('tickets.toBeResolve') }}">
                <i class="ni ni-collection text-primary"></i>
                <span class="nav-link-text">To be resolved</span>
              </a>
            </li>
            @endif

            <li class="nav-item">
              <a class="nav-link {{Request::route()->getName() == 'tickets.resolved' ? 'active' : ''}}" href="{{ route('tickets.resolved') }}">
                <i class="ni ni-check-bold text-primary"></i>
                <span class="nav-link-text">Resolved</span>
              </a>
            </li>

            @if(auth()->user()->isTeamLeader())
            <li class="nav-item mt-5">
              <div class="text-center">
                <a href="{{ route('tickets.create') }}" class="btn btn-primary btn-round">New Ticket</a>
              </div>
            </li>
            @endif

          </ul>
        </div>
      </div>
    </div>
  </nav>
@endauth

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Start your development with a Dashboard for Bootstrap 4.">
  <meta name="author" content="Creative Tim">
  <title>@yield('title', 'Ticket Management')</title>
  <!-- Favicon -->
  <link rel="icon" href="{{ asset('assets/img/brand/favicon.png')}}" type="image/png">
  <!-- Fonts -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700">
  <!-- Icons -->
  <link rel="stylesheet" href="{{ asset('assets/vendor/nucleo/css/nucleo.css')}}" type="text/css">
  <link rel="stylesheet" href="{{ asset('assets/vendor/@fortawesome/fontawesome-free/css/all.min.css')}}" type="text/css">
  <!-- Page plugins -->
  <!-- Argon CSS -->
  <link rel="stylesheet" href="{{ asset('assets/css/argon.css?v=1.2.0')}}" type="text/css">

  @yield('styles')
</head>

<body>
    <div id="app">
            @include('layouts._sidebar')

            <div class="main-content" id="panel">
                @include('layouts._navbar')

                <div class="container mt-3">
                  @include('layouts._message')
                  @yield('content')
                </div>
            </div>
    </div>

    <!-- Core -->
    <script src="{{ asset('assets/vendor/jquery/dist/jquery.min.js')}}"></script>
    <script src="{{ asset('assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js')}}"></script>
    <script src="{{ asset('assets/vendor/js-cookie/js.cookie.js')}}"></script>
    <script src="{{ asset('assets/vendor/jquery.scrollbar/jquery.scrollbar.min.js')}}"></script>
    <script src="{{ asset('assets/vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js')}}"></script>
  


    @yield('scripts')
</body>
</html>

resources/views/layouts/temp.blade.php
<!-- app.blade.php -> body -->
<nav class="navbar navbar-expand-lg navbar-dark bg-default sticky-top">
    <!-- <div class="container"> -->
        <a class="navbar-brand" href="{{ url('/') }}">
            {{ config('app.name', 'Laravel') }}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">

            </ul>

            <!-- Right Side Of Navbar -->
            @auth
            <ul class="navbar-nav ml-auto">
                @if(!auth()->user()->isTeamLeader())
                    <li class="nav-item dropdown">
                        <a class="nav-link nav-link-icon dropdown-toggle" href="javascript:;" id="navbar-default_dropdown_1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Pending</a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbar-default_dropdown_1">
                        <a class="dropdown-item" href="{{ route('tickets.assigned') }}">Assigned</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{{ route('tickets.completed') }}">Completed</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link nav-link-icon" href="{{ route('tickets.resolved') }}">Resolved</a>
                    </li>
                @endif

                @if(auth()->user()->isTeamLeader())
                    <li class="nav-item">
                        <a class="nav-link nav-link-icon" href="{{route('tickets.raised')}}">Raised</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link nav-link-icon" href="{{ route('tickets.toBeResolve') }}">To be resolve</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link nav-link-icon" href="{{ route('tickets.resolved') }}">Resolved</a>
                    </li>
                @endif

                <!-- Authentication Links -->
                @guest
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                    </li>
                    @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                    @endif
                @else
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

                            <a class="dropdown-item" href="{{ route('user.notifications') }}">
                                {{ auth()->user()->unreadNotifications->count() }} Notifications
                            </a>
                            <a class="dropdown-item" href="{{ route('logout') }}"
                                onclick="event.preventDefault();
                                                document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>  

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
            @endauth
        </div>
    <!-- </div> -->
</nav>

<main class="py-4">
@auth
    <div class="container mt-4">
        @include('layouts._message')
        <div class="row">
            <div class="col-md-12">
                @yield('content')
            </div>
        </div>
    @else
        @yield('content')
    @endauth
    </div>
</main>